In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/xyz2005/qwen-data/__huggingface_repos__.json
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/adapter_model.safetensors
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/merges.txt
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/adapter_config.json
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/README.md
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/tokenizer.json
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/vocab.json
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/tokenizer_config.json
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/special_tokens_map.json
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/added_tokens.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/adapter_model.safetensors
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/merges.txt
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/trainer_state.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/training_args.bin
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/adapter_config.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/README.md
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/tokenizer.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/vocab.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/tokenizer_config.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/scheduler.pt
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/special_tokens_map.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/optimizer.pt
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/rng_state.pth
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-867/added_tokens.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/adapter_model.safetensors
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/merges.txt
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/trainer_state.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/training_args.bin
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/adapter_config.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/README.md
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/tokenizer.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/vocab.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/tokenizer_config.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/scheduler.pt
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/special_tokens_map.json
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/optimizer.pt
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/rng_state.pth
/kaggle/input/datasets/xyz2005/qwen-data/lora_output/checkpoint-1445/added_tokens.json
/kaggle/input/datasets/xyz2005/notebook-5/training_history.csv
/kaggle/input/datasets/xyz2005/notebook-5/concept_classifier.pth
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/=0.16.0
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/concept_alignment.pth
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/adapter_model.safetensors
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/config.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/merges.txt
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/preprocessor_config.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/adapter_config.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/README.md
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/tokenizer.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/vocab.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/tokenizer_config.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/processor_config.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/special_tokens_map.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/added_tokens.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/checkpoints/lora_adapter/generation_config.json
/kaggle/input/datasets/xyz2005/conceptalignrad/ConceptAlignRad/data/clean_dataset.csv
/kaggle/input/datasets/xyz2005/concept-labels/valid_concepts.csv
/kaggle/input/datasets/xyz2005/concept-labels/test_concepts.csv
/kaggle/input/datasets/xyz2005/concept-labels/train_concepts.csv

In [2]:
!pip install -q transformers==4.46.3
!pip install -q peft==0.13.2
!pip install -q accelerate==1.1.1
!pip install -q sentencepiece

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 655.0 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 28.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 36.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 91.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.7/320.7 kB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 333.2/333.2 kB 2.0 MB/s eta 0:00:00

In [3]:
!pip install -U bitsandbytes==0.46.1

Collecting bitsandbytes==0.46.1
  Downloading bitsandbytes-0.46.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.2 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes==0.46.1) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes==0.46.1) (2.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.2->bitsandbytes==0.46.1) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch<3,>=2.2->bitsandbytes==0.46.1) (1.5.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.2->bitsandbytes==0.46.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.2->bitsandbytes==0.46.1) (3.0.3)
Downloading bitsandbytes-0.46.1-py3-none-manylinux_2_24_x86_64.whl (72.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 MB 22.2 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.46.1

In [4]:
import torch
import transformers
import peft
import accelerate
import pandas as pd

print("Transformers :", transformers.__version__)
print("PEFT         :", peft.__version__)
print("Accelerate   :", accelerate.__version__)
print("Torch        :", torch.__version__)

print("\nCUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("GPU Memory:",
          torch.cuda.get_device_properties(0).total_memory / 1024**3,
          "GB")

Transformers : 4.46.3
PEFT         : 0.13.2
Accelerate   : 1.1.1
Torch        : 2.10.0+cu128

CUDA available: True
GPU: Tesla T4
GPU Memory: 14.56219482421875 GB

In [5]:
import os
import glob
import pandas as pd
import torch

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig
)

from peft import PeftModel

In [6]:
import os
import glob

adapter_files = glob.glob(
    "/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/adapter_config.json",
    recursive=True
)

print("Found adapter files:")

for f in adapter_files:
    print(f)

Found adapter files:
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora/adapter_config.json

In [7]:
assert len(adapter_files) > 0, "LoRA adapter not found!"

LORA_PATH = os.path.dirname(adapter_files[0])

print("LoRA path:")
print(LORA_PATH)

print("\nFiles:")
print(os.listdir(LORA_PATH))

LoRA path:
/kaggle/input/datasets/xyz2005/qwen-data/qwen_lora

Files:
['adapter_model.safetensors', 'merges.txt', 'adapter_config.json', 'README.md', 'tokenizer.json', 'vocab.json', 'tokenizer_config.json', 'special_tokens_map.json', 'added_tokens.json']

In [8]:
test_files = glob.glob(
    "/kaggle/input/datasets/xyz2005/concept-labels/test_concepts.csv",
    recursive=True
)

print("Found test files:")

for f in test_files:
    print(f)

Found test files:
/kaggle/input/datasets/xyz2005/concept-labels/test_concepts.csv

In [9]:
assert len(test_files) > 0, "test_concepts.csv not found!"

TEST_CSV = test_files[0]

print("Using:")
print(TEST_CSV)

Using:
/kaggle/input/datasets/xyz2005/concept-labels/test_concepts.csv

In [10]:
test_df = pd.read_csv(TEST_CSV)

print("Shape:", test_df.shape)

print("\nColumns:")
print(test_df.columns.tolist())

print("\nFirst 2 rows:")
display(test_df.head(2))

Shape: (496, 11)

Columns:
['report', 'Pneumonia', 'Cardiomegaly', 'Pleural Effusion', 'Atelectasis', 'Edema', 'Pneumothorax', 'Consolidation', 'Lung Opacity', 'Nodule', 'Mass']

First 2 rows:

,report,Pneumonia,Cardiomegaly,Pleural Effusion,Atelectasis,Edema,Pneumothorax,Consolidation,Lung Opacity,Nodule,Mass
0,stable appearance of hiatal hernia. clear righ...,0,0,1,0,0,1,0,0,0,1
1,heart size normal. lungs are clear. xxxx are n...,1,0,1,0,1,1,0,0,1,1

In [11]:
LABELS = [
    "Pneumonia",
    "Cardiomegaly",
    "Pleural Effusion",
    "Atelectasis",
    "Edema",
    "Pneumothorax",
    "Consolidation",
    "Lung Opacity",
    "Nodule",
    "Mass"
]

In [12]:
MODEL_NAME = "Qwen/Qwen2.5-1.5B"

tokenizer = AutoTokenizer.from_pretrained(
    LORA_PATH,
    trust_remote_code=True
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "left"

print("Tokenizer loaded successfully")
print("Pad token:", tokenizer.pad_token)
print("EOS token:", tokenizer.eos_token)

Tokenizer loaded successfully
Pad token: <|endoftext|>
EOS token: <|endoftext|>

In [13]:
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

print("4-bit configuration ready")

4-bit configuration ready

In [14]:
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

print("Base Qwen model loaded")

config.json:   0%|          | 0.00/684 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/138 [00:00<?, ?B/s]

Base Qwen model loaded

In [15]:
model = PeftModel.from_pretrained(
    base_model,
    LORA_PATH
)

model.eval()

print("LoRA adapter loaded successfully!")

LoRA adapter loaded successfully!

In [16]:
model.print_trainable_parameters()

trainable params: 0 || all params: 1,562,179,072 || trainable%: 0.0000

In [17]:
def create_inference_prompt(row):

    findings = []

    for disease in LABELS:
        if int(row[disease]) == 1:
            findings.append(disease)

    if len(findings) == 0:
        findings.append("No significant abnormality")

    findings_text = "\n".join(
        [f"- {x}" for x in findings]
    )

    prompt = f"""### System
You are an expert radiologist specializing in chest X-ray interpretation.

### User
Generate a professional radiology report from the following findings.

Findings:
{findings_text}

### Assistant
"""

    return prompt

In [18]:
sample = test_df.iloc[0]

prompt = create_inference_prompt(sample)

print(prompt)

### System
You are an expert radiologist specializing in chest X-ray interpretation.

### User
Generate a professional radiology report from the following findings.

Findings:
- Pleural Effusion
- Pneumothorax
- Mass

### Assistant

In [19]:
inputs = tokenizer(
    prompt,
    return_tensors="pt",
    truncation=True,
    max_length=512
)

inputs = {
    k: v.to(model.device)
    for k, v in inputs.items()
}

with torch.no_grad():

    output_ids = model.generate(
        **inputs,
        max_new_tokens=180,
        do_sample=False,
        temperature=1.0,
        top_p=1.0,
        repetition_penalty=1.1,
        pad_token_id=tokenizer.pad_token_id,
        eos_token_id=tokenizer.eos_token_id
    )

generated_text = tokenizer.decode(
    output_ids[0],
    skip_special_tokens=True
)

print(generated_text)

### System
You are an expert radiologist specializing in chest X-ray interpretation.

### User
Generate a professional radiology report from the following findings.

Findings:
- Pleural Effusion
- Pneumothorax
- Mass

### Assistant
the heart size is normal. lungs are clear bilaterally. there is no pleural line to suggest pneumothorax or costophrenic xxxx blunting to suggest large pleural effusion. there is no focal infiltrate. bony structures are within normal limits. no acute cardiopulmonary finding. . 1. no acute cardiopulmonary process. 2. no evidence for metastatic disease by known primary. if clinically indicated, further imaging of the chest may be helpful. . dr. xxxxx xxxx was called and notified of these results at xxxx p.m. xxxx xxxx. xxxx receipt of this report. dr. xxxxxxxx xxxx will notify me of any questions regarding this result. thank you for choosing xxxx as your medical specialty provider. xxxx xxxx xxxx. dr. xxxxxx xxxx xxxx at xxxx p.m. xxxx xxxx with notification of these results. xxxx

In [20]:
def extract_report(text):

    if "### Assistant" in text:
        text = text.split("### Assistant", 1)[1]

    return text.strip()

In [21]:
generated_report = extract_report(generated_text)

print("Generated Report:\n")
print(generated_report)

Generated Report:

the heart size is normal. lungs are clear bilaterally. there is no pleural line to suggest pneumothorax or costophrenic xxxx blunting to suggest large pleural effusion. there is no focal infiltrate. bony structures are within normal limits. no acute cardiopulmonary finding. . 1. no acute cardiopulmonary process. 2. no evidence for metastatic disease by known primary. if clinically indicated, further imaging of the chest may be helpful. . dr. xxxxx xxxx was called and notified of these results at xxxx p.m. xxxx xxxx. xxxx receipt of this report. dr. xxxxxxxx xxxx will notify me of any questions regarding this result. thank you for choosing xxxx as your medical specialty provider. xxxx xxxx xxxx. dr. xxxxxx xxxx xxxx at xxxx p.m. xxxx xxxx with notification of these results. xxxx

In [22]:
print("===== GENERATED REPORT =====")
print(generated_report)

print("\n===== GROUND TRUTH REPORT =====")
print(sample["report"])

===== GENERATED REPORT =====
the heart size is normal. lungs are clear bilaterally. there is no pleural line to suggest pneumothorax or costophrenic xxxx blunting to suggest large pleural effusion. there is no focal infiltrate. bony structures are within normal limits. no acute cardiopulmonary finding. . 1. no acute cardiopulmonary process. 2. no evidence for metastatic disease by known primary. if clinically indicated, further imaging of the chest may be helpful. . dr. xxxxx xxxx was called and notified of these results at xxxx p.m. xxxx xxxx. xxxx receipt of this report. dr. xxxxxxxx xxxx will notify me of any questions regarding this result. thank you for choosing xxxx as your medical specialty provider. xxxx xxxx xxxx. dr. xxxxxx xxxx xxxx at xxxx p.m. xxxx xxxx with notification of these results. xxxx

===== GROUND TRUTH REPORT =====
stable appearance of hiatal hernia. clear right lung xxxx.in the left superior lower lobe there is a 1.9 x 1.8 cm round area of density which has increased in size compared to prior chest radiograph and recommend a xxxx chest, abdomen and pelvis with contrast as this area is suspicious for potential malignancy. normal cardiac contour. no pneumothorax or pleural effusion. 1. round area of density measuring 1.9 x 1.8 cm in left superior lower lobe with interval increased size compared to prior imaging. recommend xxxx chest, abdomen and pelvis with contrast for further evaluation. dr. xxxx xxxx notified by the veriphy critical result notification xxxx of the left pulmonary mass and recommended followup xxxx chest, abdomen and pelvis with contrast at xxxx xxxxxxxx.

In [23]:
def generate_report(findings, max_new_tokens=100):

    findings_text = "\n".join(
        [f"- {finding}" for finding in findings]
    )

    prompt = f"""### System
You are an expert radiologist specializing in chest X-ray interpretation.

Generate a concise professional radiology report from the following findings.

### User
Findings:
{findings_text}

### Assistant
"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    )

    inputs = {
        key: value.to(model.device)
        for key, value in inputs.items()
    }

    with torch.no_grad():

        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,

            # Reduce repetition
            repetition_penalty=1.2,
            no_repeat_ngram_size=3,

            # Stop generation when EOS is produced
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id
        )

    generated_text = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    if "### Assistant" in generated_text:
        generated_text = generated_text.split(
            "### Assistant", 1
        )[-1]

    return generated_text.strip()

In [24]:
results = []

for i in range(min(10, len(test_df))):

    print(f"Generating report {i+1}/10...")

    generated = generate_report(test_df.iloc[i])

    results.append(generated)

print("\nGeneration completed!")

Generating report 1/10...
Generating report 2/10...
Generating report 3/10...
Generating report 4/10...
Generating report 5/10...
Generating report 6/10...
Generating report 7/10...
Generating report 8/10...
Generating report 9/10...
Generating report 10/10...

Generation completed!

In [25]:
for i in range(len(results)):

    print("=" * 80)

    print(f"CASE {i+1}")

    print("\nGENERATED:")
    print(results[i])

    print("\nGROUND TRUTH:")
    print(test_df.iloc[i]["report"])

    print()

================================================================================
CASE 1

GENERATED:
the heart size remains within normal limits. the lungs remain grossly clear without evidence for acute infiltrate or significant change since comparison study was performed on xxxx. however, there appears to be some increase in prominence of the mediastinal contours bilaterally suggesting mild vascular congestion versus perihilar opacities consistent with emphysema. additionally, there may have been slight improvement in visualized hiatal hiatus hernia noted previously. otherwise, no definite metastatic disease identified. if clinically indicated consider

GROUND TRUTH:
stable appearance of hiatal hernia. clear right lung xxxx.in the left superior lower lobe there is a 1.9 x 1.8 cm round area of density which has increased in size compared to prior chest radiograph and recommend a xxxx chest, abdomen and pelvis with contrast as this area is suspicious for potential malignancy. normal cardiac contour. no pneumothorax or pleural effusion. 1. round area of density measuring 1.9 x 1.8 cm in left superior lower lobe with interval increased size compared to prior imaging. recommend xxxx chest, abdomen and pelvis with contrast for further evaluation. dr. xxxx xxxx notified by the veriphy critical result notification xxxx of the left pulmonary mass and recommended followup xxxx chest, abdomen and pelvis with contrast at xxxx xxxxxxxx.

================================================================================
CASE 2

GENERATED:
the cardiac silhouette is near top normal in size with mild thoracic spondylosis and degenerative changes at multiple levels along the spine. there appears to be some scarring within both lung bases without any acute infiltrate or pleural effusion. no displaced rib fractures identified. 2. scattered calcified granulomas throughout both lower lobes consistent with prior granulomatous disease versus chronic infection. otherwise pulmonary vasculature is unremarkable. 3. right upper quadrant surgical

GROUND TRUTH:
heart size normal. lungs are clear. xxxx are normal. no pneumonia, effusions, edema, pneumothorax, adenopathy, nodules or masses. normal chest no evidence of tuberculosis.

================================================================================
CASE 3

GENERATED:
the cardiac silhouette measures upper limit of normal for ap projection, but stable compared to prior study. central vascular markings consistent with low lung volumes versus bronchovascular crowding. otherwise, pulmonary vasculature appears unremarkable. calcified granuloma present on lateral view xxxx reflects old cavitary lesion. leftsided picc line has been placed at the level of the inferior svc junction. catheter tip terminates near mid superior mesenteric vein. this would be compatible with postoperative

GROUND TRUTH:
the heart size and pulmonary vascularity appear within normal limits.the lungs are free of focal airspace disease. no pleural effusion or pneumothorax is seen. there is eventration of the right hemidiaphragm. the descending thoracic aorta is tortuous. 1. no evidence of active disease.

================================================================================
CASE 4

GENERATED:
the heart is topologically xxxx but otherwise appears normal. there is mild tortuosity of the thoracic aorta, unchanged since prior study. calcified granuloma at the right lung base remains stable compared to previous exam. visualized osseous structures appear grossly intact with no evidence for fracture or dislocation. 1. no definite acute pulmonary finding. . 2. persistent appearance of left basilar airspace disease as described above. this may be related to aspiration versus infection although further

GROUND TRUTH:
cardiac and mediastinal contours are within normal limits. the lungs are clear. bony structures are intact. no acute findings.

================================================================================
CASE 5

GENERATED:
the lungs appear clear. there is mild hyperexpansion consistent with emphysema. calcified granuloma seen within the left lower lobe. otherwise normal cardiac silhouette and mediastinal contours. visualized osseous structures intact without fracture or dislocation. stable appearance compared to prior study dated october 21st , 2014 . no acute pulmonary process identified. if further concern for occult pulmonary pathology consider dedicated xxxxx examination.. 1. no acute cardiob

GROUND TRUTH:
heart xxxx, mediastinum, xxxx, bony structures and lung xxxx are unremarkable. no radiographic evidence of acute cardiopulmonary disease

================================================================================
CASE 6

GENERATED:
the xxxx examination consists of frontal and lateral radiographs of the chest. two sets were obtained, one on each side. both examinations have been placed together for display. the images show the results of study xxxxx as described above. again noted is that the cardiac silhouette remains within normal limits while mild tortuosity of the thoracic aorta appears unchanged since previous exam dated october 29th, 1987. also apparent is continued leftsided picc line with tip at

GROUND TRUTH:
the lungs are clear. there is no pleural effusion or pneumothorax. the heart and mediastinum are normal. the skeletal structures are normal. no acute pulmonary disease.

================================================================================
CASE 7

GENERATED:
the heart size remains mildly enlarged with stable appearance of bilateral basilar opacities which could represent infiltrate versus superimposed shadows on film. this cannot be definitively determined without comparison to prior studies if available clinical correlation would also be helpful given differential diagnosis including infection vs inflammation, aspiration, foreign body etc..copd again demonstrated. .right basilar focal airspace disease suggested as above however further evaluation by dedicated lung xxxxx study recommended. results can be discussed during your next scheduled appointment. alternatively,

GROUND TRUTH:
frontal and lateral views of the chest show an unchanged cardiomediastinal silhouette. rightsided aortic xxxx. normal mediastinal contour, pulmonary xxxx and vasculature, central airways and aeration of the lungs. there is right basal xxxx patchy opacity and bibasal atelectasis or scarring. there is no pleural effusion or pneumothorax. right apical calcified granuloma noted. 1. right basal acute airspace disease. please correlate clinically for pneumonia. 2. chronic interstitial pattern, may reflect copd.

================================================================================
CASE 8

GENERATED:
the lungs appear clear. however, if one wishes to be absolutely certain that there has been no focal airspace consolidation then consider obtaining lateral films as well for comparison or use dedicated small volume lung volumes techniques such as low dose ct scanning with appropriate selection and exclusion criteria. this would also allow better visualization of any possible pleural fluid collections. .if concerned about pulmonary embolism recommend further evaluation using methods described above. otherwise no definite acute cardiogenic process identified. compare these results with prior studies if available.

GROUND TRUTH:
normal cardiomediastinal silhouette. there is no focal consolidation. there are no xxxx of a large pleural effusion. there is no pneumothorax. there is no acute bony abnormality seen. there is no radiographic evidence of acute cardiopulmonary disease.

================================================================================
CASE 9

GENERATED:
the lung volumes remain low, but have improved slightly compared to prior study. this is consistent with improvement in copd symptoms as evidenced by clinical history. however, stable appearance of bilateral interstitial markings which may reflect continuedcopd process versus other differential diagnoses such as infection or inflammation. further evaluation could be performed including ct thorax for additional characterization if clinically indicated. .chronic changes without acute abnormality identified. consider followup after appropriate therapy has been initiated. results were forwarded to patient at xxxx pm

GROUND TRUTH:
borderline heart size. the lungs are hyperexpanded and hyperlucent compatible with chronic obstructive pulmonary disease. there are no xxxx focal air space consolidations. no pleural effusions or pneumothoraces. the hilar and mediastinal contours are unchanged. aortic vascular calcifications. normal pulmonary vascularity. bone demineralization. findings of chronic obstructive pulmonary disease.

================================================================================
CASE 10

GENERATED:
the lungs and pleural spaces show no acute abnormality. there is mild tortuosity of the thoracic aorta with calcified mediastinal lymph xxxx, consistent with prior granulomatous disease. stable leftsided picc line overlying the right subclavian vein at approximately midline. 2 cm catheter tip above the level of the carina. . 1. no active pulmonary process. 0. clear lungs. 1.. unchanged large central venous cath

GROUND TRUTH:
heart size within normal limits. no focal airspace disease. no pneumothorax or effusions. no acute cardiopulmonary findings.

In [26]:
generated_reports = []

for i in range(len(test_df)):

    if i % 25 == 0:
        print(f"Processing {i}/{len(test_df)}")

    report = generate_report(test_df.iloc[i])

    generated_reports.append(report)

print("All reports generated!")

Processing 0/496
Processing 25/496
Processing 50/496
Processing 75/496
Processing 100/496
Processing 125/496
Processing 150/496
Processing 175/496
Processing 200/496
Processing 225/496
Processing 250/496
Processing 275/496
Processing 300/496
Processing 325/496
Processing 350/496
Processing 375/496
Processing 400/496
Processing 425/496
Processing 450/496
Processing 475/496
All reports generated!

In [27]:
results_df = test_df.copy()

results_df["generated_report"] = generated_reports

print(results_df.shape)

display(
    results_df[
        ["report", "generated_report"]
    ].head()
)

(496, 12)

,report,generated_report
0,stable appearance of hiatal hernia. clear righ...,the heart size remains within normal limits. t...
1,heart size normal. lungs are clear. xxxx are n...,the cardiac silhouette is near top normal in s...
2,the heart size and pulmonary vascularity appea...,the cardiac silhouette measures upper limit of...
3,cardiac and mediastinal contours are within no...,the heart is topologically xxxx but otherwise ...
4,"heart xxxx, mediastinum, xxxx, bony structures...",the lungs appear clear. there is mild hyperexp...

In [28]:
OUTPUT_PATH = "/kaggle/working/generated_reports.csv"

results_df.to_csv(
    OUTPUT_PATH,
    index=False
)

print("Saved:")
print(OUTPUT_PATH)

Saved:
/kaggle/working/generated_reports.csv

In [29]:
evaluation_df = results_df[
    ["report", "generated_report"]
].copy()

evaluation_df.to_csv(
    "/kaggle/working/report_generation_results.csv",
    index=False
)

print("Evaluation file saved!")

Evaluation file saved!

In [30]:
import os

print(os.listdir("/kaggle/working"))

['__notebook__.ipynb', 'generated_reports.csv', 'report_generation_results.csv']

In [31]:
import shutil

shutil.make_archive(
    "/kaggle/working/notebook7_results",
    "zip",
    "/kaggle/working",
    base_dir="."
)

print("ZIP created:")
print("/kaggle/working/notebook7_results.zip")

ZIP created:
/kaggle/working/notebook7_results.zip